map convert
kingsawpdx/virtualFieldEnvironments pull request #29
Opened 2024-03-03 23:20 UTC by Kuro2709

modify map conversion function

2024-03-05 00:58 UTC, kingsawpdx approved these changes
Looks good to me!

2024-03-05 05:58 UTC, mnxn requested changes

2024-03-05 05:58 UTC, mnxn commented on src/DataStructures.ts
> +  rotation: string;
As mentioned in the meeting, the `rotation` field should have a `number` type.

2024-03-14 01:03 UTC, mnxn requested changes

2024-03-14 01:03 UTC, mnxn commented on src/App.tsx
> +    rotation: parseInt("0deg"),
This line should just be `rotation: 0`.

2024-03-14 01:09 UTC, mnxn approved these changes
Looks good.

2024-03-15 20:39 UTC, merged